name: PotatoWarp
version: ${project.version}
main: me.bigvirusboi.potatowarp.PotatoWarp
api-version: 1.17
authors: [BigVirusBoi]
description: A simple warp plugin!
commands:
  warp:
    permission: potatowarp.warp
    description: The command used to warp
  warps:
    permission: potatowarp.warp.list
    description: The command used to list all warps
  setwarp:
    permission: potatowarp.warp.create
    description: The command used to create a warp
  delwarp:
    permission: potatowarp.warp.delete
    description: The command used to delete a warp
