name: PotatoWarp
version: ${project.version}
main: me.bigvirusboi.potatowarp.PotatoWarp
api-version: 1.17
authors: [BigVirusBoi]
description: A simple warp plugin!
commands:
  warp:
    permission: potatowarp.warp
    description: The command used to warp
  warps:
    permission: potatowarp.warps
    description: The command used to list all warps
    aliases:
      - listwarps
      - warplist
  setwarp:
    permission: potatowarp.setwarp
    description: The command used to create a warp
    aliases:
      - addwarp
      - createwarp
  delwarp:
    permission: potatowarp.delwarp
    description: The command used to delete a warp
    aliases:
      - removewarp
      - deletewarp
